name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

permissions:
  contents: write  # Allows actions to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a Node.js version compatible with Nuxt 3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run generate  # Generates static site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .output/public  # Nuxt 3 generates static files here
          github_token: ${{ secrets.GITHUB_TOKEN }}